"""Independent verification for generated ODD-002 diff artifacts."""

from __future__ import annotations

import json
from collections.abc import Callable
from datetime import UTC, datetime

from odd.diffs.engine import DiffEngine
from odd.errors import SourceNotFound
from odd.models import DiffVerificationCheck, DiffVerificationResult
from odd.provenance.canonical import canonical_diff_json_bytes, canonical_json_bytes
from odd.provenance.hashing import sha256_bytes
from odd.provenance.identifiers import section_diff_id
from odd.storage.sqlite import SQLiteRepository
from odd.validation.verify import Verifier
from odd.versioning import determine_version_order


class DiffVerifier:
    def __init__(
        self,
        repository: SQLiteRepository,
        engine: DiffEngine | None = None,
        clock: Callable[[], datetime] | None = None,
    ) -> None:
        self.repository = repository
        self.engine = engine or DiffEngine()
        self.clock = clock or (lambda: datetime.now(UTC))

    def verify(self, diff_id: str) -> DiffVerificationResult:
        record = self.repository.get_diff_artifact(diff_id)
        if record is None:
            raise SourceNotFound("diff artifact was not found", details={"diff_id": diff_id})
        checks: list[DiffVerificationCheck] = []
        canonical = bytes(record["canonical_json"])
        actual_sha = sha256_bytes(canonical)
        artifact_hash_ok = actual_sha == record["canonical_sha256"]
        checks.append(
            DiffVerificationCheck(
                name="canonical_artifact_sha256",
                ok=artifact_hash_ok,
                message=f"canonical diff SHA-256 verified: {actual_sha}"
                if artifact_hash_ok
                else (
                    "canonical diff SHA-256 mismatch: "
                    f"expected {record['canonical_sha256']}, got {actual_sha}"
                ),
            )
        )

        try:
            payload = json.loads(canonical)
            json_ok = isinstance(payload, dict) and payload.get("diff_id") == diff_id
            json_message = (
                "canonical diff JSON and diff identity verified"
                if json_ok
                else "canonical diff JSON does not match its stored identity"
            )
        except (UnicodeDecodeError, json.JSONDecodeError) as exc:
            payload = {}
            json_ok = False
            json_message = f"canonical diff JSON is malformed: {exc}"
        checks.append(DiffVerificationCheck("canonical_artifact_json", json_ok, json_message))

        engine_ok = str(record["diff_engine_version"]) == self.engine.version
        checks.append(
            DiffVerificationCheck(
                name="diff_engine_version",
                ok=engine_ok,
                message=f"diff engine version supported: {self.engine.version}"
                if engine_ok
                else (
                    f"unsupported stored diff engine {record['diff_engine_version']}; "
                    f"runtime supports {self.engine.version}"
                ),
            )
        )

        regenerated = None
        reproduction_message = "artifact JSON or diff engine version is unsupported"
        reproduction_ok = False
        deterministic_timestamp_ok = False
        if json_ok and engine_ok:
            try:
                old = (
                    self.repository.get_stored_document(str(record["old_document_id"]))
                    if record["old_document_id"]
                    else None
                )
                new = (
                    self.repository.get_stored_document(str(record["new_document_id"]))
                    if record["new_document_id"]
                    else None
                )
                ordering_payload = payload.get("ordering", {})
                snapshot_id = (
                    str(ordering_payload.get("history_snapshot_id"))
                    if ordering_payload.get("history_snapshot_id")
                    else None
                )
                _selected, entries = self.repository.get_history_entries(
                    str(record["lineage_id"]), snapshot_id
                )
                ordering = determine_version_order(
                    old,
                    new,
                    history_entries=entries,
                    history_snapshot_id=snapshot_id,
                )
                generated_at = self._now()
                regenerated = self.engine.generate(
                    old, new, ordering=ordering, generated_at=generated_at
                )
                reproduced_bytes = canonical_diff_json_bytes(regenerated)
                reproduction_ok = reproduced_bytes == canonical
                reproduction_message = (
                    "canonical diff regenerated byte-for-byte from stored source versions"
                    if reproduction_ok
                    else "regenerated canonical diff differs from the stored artifact"
                )
                second = self.engine.generate(
                    old,
                    new,
                    ordering=ordering,
                    generated_at=generated_at.replace(
                        microsecond=(generated_at.microsecond + 1) % 1_000_000
                    ),
                )
                deterministic_timestamp_ok = (
                    canonical_diff_json_bytes(second) == reproduced_bytes
                )
            except Exception as exc:  # verification reports rather than hiding the failed check
                reproduction_message = f"diff reproduction failed: {exc}"
        checks.append(
            DiffVerificationCheck(
                "deterministic_diff_reproduction", reproduction_ok, reproduction_message
            )
        )
        checks.append(
            DiffVerificationCheck(
                name="generation_timestamp_excluded",
                ok=deterministic_timestamp_ok,
                message="generated_at does not affect canonical diff bytes"
                if deterministic_timestamp_ok
                else "generated_at independence could not be verified",
            )
        )

        section_ok = False
        section_message = "diff could not be regenerated"
        if regenerated is not None:
            rows = self.repository.get_section_diff_artifacts(diff_id)
            failures: list[str] = []
            if len(rows) != len(regenerated.section_diffs):
                failures.append(
                    f"expected {len(regenerated.section_diffs)} rows, found {len(rows)}"
                )
            for index, (row, section) in enumerate(
                zip(rows, regenerated.section_diffs, strict=False)
            ):
                expected_json = canonical_json_bytes(section)
                expected_id = section_diff_id(diff_id, index)
                if row["id"] != expected_id:
                    failures.append(f"row {index} identifier mismatch")
                if bytes(row["canonical_json"]) != expected_json:
                    failures.append(f"row {index} canonical JSON mismatch")
                if row["canonical_sha256"] != sha256_bytes(expected_json):
                    failures.append(f"row {index} SHA-256 mismatch")
            section_ok = not failures
            section_message = (
                f"verified {len(rows)} stored section-diff rows"
                if section_ok
                else "; ".join(failures)
            )
        checks.append(DiffVerificationCheck("section_diff_artifacts", section_ok, section_message))

        try:
            integrity = self.repository.diff_integrity_checks(diff_id)
            database_ok = (
                integrity["integrity_check"] == "ok"
                and not integrity["foreign_key_violations"]
                and integrity["diff_count"] == 1
            )
            database_message = f"SQLite diff integrity: {integrity}"
        except Exception as exc:
            database_ok = False
            database_message = f"SQLite diff integrity check failed: {exc}"
        checks.append(DiffVerificationCheck("database_consistency", database_ok, database_message))

        source_results = []
        try:
            for document_id in (record["old_document_id"], record["new_document_id"]):
                if document_id:
                    source_results.append(Verifier(self.repository).verify(str(document_id)))
            sources_ok = bool(source_results) and all(item.ok for item in source_results)
            source_message = f"verified {len(source_results)} compared normalized source documents"
        except Exception as exc:
            sources_ok = False
            source_message = f"compared source verification failed: {exc}"
        checks.append(
            DiffVerificationCheck("compared_source_documents", sources_ok, source_message)
        )
        return DiffVerificationResult(
            diff_id=diff_id,
            ok=all(item.ok for item in checks),
            checks=tuple(checks),
        )

    def _now(self) -> datetime:
        value = self.clock()
        aware = value if value.tzinfo is not None else value.replace(tzinfo=UTC)
        return aware.astimezone(UTC)
